/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#1d4ed8",
        "secondary": "#0ea5e9",
        "primary-fixed": "#dbeafe",
        "tertiary-fixed": "#d8e2ff",
        "on-tertiary-fixed": "#001a42",
        "outline-variant": "#c7c4d7",
        "on-primary-container": "#fffbff",
        "error": "#ba1a1a",
        "inverse-surface": "#2d3133",
        "on-primary": "#ffffff",
        "on-surface": "#191c1e",
        "background": "#f7f9fb",
        "on-secondary-fixed-variant": "#0284c7",
        "surface-tint": "#2563eb",
        "on-secondary-container": "#fffbff",
        "on-tertiary": "#ffffff",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#2170e4",
        "on-error": "#ffffff",
        "surface-dim": "#d8dadc",
        "outline": "#767586",
        "primary-fixed-dim": "#93c5fd",
        "surface-variant": "#e0e3e5",
        "primary-container": "#3b82f6",
        "on-secondary": "#ffffff",
        "primary": "#2563eb",
        "secondary-fixed-dim": "#bae6fd",
        "on-primary-fixed": "#002d8c",
        "on-tertiary-fixed-variant": "#004395",
        "secondary-container": "#bae6fd",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#adc6ff",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#fefcff",
        "tertiary": "#0058be",
        "surface-bright": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "surface": "#f7f9fb",
        "inverse-primary": "#93c5fd",
        "secondary-fixed": "#e0f2fe",
        "on-secondary-fixed": "#0c4a6e",
        "surface-container-high": "#e6e8ea",
        "card-foreground": "hsl(var(--card-foreground) / <alpha-value>)",
        "card": "hsl(var(--card) / <alpha-value>)",
        "on-surface-variant": "#464554"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "24px",
        "margin-md": "32px",
        "base": "8px",
        "gutter": "20px",
        "margin-sm": "16px",
        "margin-lg": "48px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display": ["Plus Jakarta Sans"],
        "label-sm": ["Manrope"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
